<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class AnimeGenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('anime_genres')->insert([
            'id_anime'=>1,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>1,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>1,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>1,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>2,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>2,
            'id_genre'=>2,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>3,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>3,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>3,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>4,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>4,
            'id_genre'=>6,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>4,
            'id_genre'=>7,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>5,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>5,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>5,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>6,
            'id_genre'=>2,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>7,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>8,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>8,
            'id_genre'=>8,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>9,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>9,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>10,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>10,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>11,
            'id_genre'=>9,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>12,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>12,
            'id_genre'=>8,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>13,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>13,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>14,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>14,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>15,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>15,
            'id_genre'=>6,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>16,
            'id_genre'=>9,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>17,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>17,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>17,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>18,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>19,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>19,
            'id_genre'=>9,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>20,
            'id_genre'=>10,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>21,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>21,
            'id_genre'=>2,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>22,
            'id_genre'=>2,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>22,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>23,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>23,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>23,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>24,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>24,
            'id_genre'=>4,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>24,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>24,
            'id_genre'=>10,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>24,
            'id_genre'=>6,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>25,
            'id_genre'=>3,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>25,
            'id_genre'=>5,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>25,
            'id_genre'=>10,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>25,
            'id_genre'=>11,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>25,
            'id_genre'=>8,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>26,
            'id_genre'=>9,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>27,
            'id_genre'=>1,
        ]);
        DB::table('anime_genres')->insert([
            'id_anime'=>27,
            'id_genre'=>5,
        ]);
    }
}
